name: Update Docs

on:
  push:
    branches: [main]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "gh-pages"

      - name: Create conda environment
        run: conda create --quiet -c conda-forge --name viz

      - name: Install River and Dependencies
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          root=$PWD
          source activate viz
          cd /tmp
          git clone https://github.com/online-ml/viz
          cd viz
          conda install pandoc
          pip install -r requirements.txt
          make html
          mv $root/.git _build/html/.git
          rm -rf $root
          mv _build/html $root
          cd $root
          touch .nojekyll
          ls

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: .
